### ISSUE TITLE
how to spoof the origin phone number ! ? 

### ISSUE THREAD

**Issue by darkhacknet** [hirusha-adi/SMS-Sending-Discord-Bot#1]
Hello,  

Man I have this working fine but, I have a question, telnyx is allowing spoofed calls so I was thinking about how to send spoofed messages. I mean with the origin phone number modified ... have you some idea ? 

Thanks ! 

Regards. !

**Comment by hirusha-adi** [comment]
i think you need to deal with telnyx in your end to do it

**Comment by darkhacknet** [comment]
> i think you need to deal with telnyx in your end to do it

OK I will take a look. Thanks
